movies1 = [
    "3 Idiots",
    "Dangal",
    "Taare Zameen Par",
    "Black Friday",
    "Gangs of Wasseypur",
    "Chhichhore",
    "Queen",
    "Andhadhun",
    "Drishyam",
    "Barfi!",
    "Paan Singh Tomar",
    "Lagaan",
    "Munna Bhai MBBS",
    "Swades",
    "Zindagi Na Milegi Dobara",
    "Rang De Basanti",
    "Dil Chahta Hai",
    "PK",
    "Kahaani",
    "Haider",
    "Shershaah",
    "Super 30",
    "Article 15",
    "Bajrangi Bhaijaan",
    "Tumbbad",
    "The Lunchbox",
    "Masaan",
    "Udaan",
    "Raazi",
    "Chak De India",
    "My Name is Khan",
    "A Wednesday!",
    "Bhaag Milkha Bhaag",
    "Parmanu",
    "Special 26",
    "Manjhi The Mountain Man",
    "Dilwale Dulhania Le Jayenge",
    "Hum Aapke Hain Koun",
    "Kabhi Khushi Kabhie Gham",
    "Kal Ho Naa Ho",
    "Yeh Jawaani Hai Deewani",
    "Rockstar",
    "Tamasha",
    "Dear Zindagi",
    "Neerja",
    "Jab We Met",
    "Om Shanti Om",
    "Bhool Bhulaiyaa",
    "Padman",
    "Toilet Ek Prem Katha",
    "Kesari",
    "Sanju",
    "War",
    "Talaash",
    "Madras Cafe",
    "Batla House",
    "Shootout at Lokhandwala",
    "Kaabil",
    "Badla",
    "Pink",
    "Sarbjit",
    "Rock On",
    "Guru",
    "Johnny Gaddaar",
    "Don (2006)",
    "Sholay",
    "Deewaar",
    "Mughal-e-Azam",
    "Pyaasa",
    "Anand",
    "Gol Maal",
    "Chupke Chupke",
    "Jaane Bhi Do Yaaro"
]
movies = [movie.lower() for movie in movies1]
